# This is a basic workflow to help you get started with Actions

name: Deploy Azure Resources 
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ] 
    paths-ignore: [".github/workflows/*", "*.ps1"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env: 
  Az_RG_Name: RGWorkflow
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run bicep linter test 
        run: az bicep build --file storage.bicep
  deploy: 
    runs-on: ubuntu-latest
    needs: [lint]
    steps: 
      - uses: actions/checkout@v3
      - name: sign in to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Create RG
        uses: azure/cli@v1
        with: 
          inlineScript: az group create --name ${{env.Az_RG_Name}} --location 'WestEurope'
      - name: Deploy Storage Account
        uses: azure/arm-deploy@v1
        id: deploy-sa
        with: 
          deploymentName: ${{github.run_number}}
          resourceGroupName: ${{env.Az_RG_Name}} 
          template: ./storage.bicep 

      - name: Deploy Container
        uses: azure/arm-deploy@v1
        id: deploy-sa-container
        with: 
          deploymentName: ${{github.run_number}}
          resourceGroupName: ${{env.Az_RG_Name}} 
          template: ./blobcontainer.bicep
          parameters: mysaname=${{steps.deploy-sa.output.mysaname}}